version: '3.9'

services:
    postgresql:
        image: library/postgres:13-alpine
        container_name: "postgresql"
        ports:
            - 5432:5432 # expose portu pro použití z venku
        environment:
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_DB=database
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=password
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"
            - "/docker/lednice/postgres-scripts:/docker-entrypoint-initdb.d"
            - "/docker_volumes/postgres:/var/lib/postgresql/data"

networks:
  default:
    external:
      name: phpwell_network
